# Generated by Django 4.1.3 on 2022-11-19 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
                ('pan', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('policyno', models.CharField(max_length=6)),
                ('premium', models.IntegerField()),
                ('brand', models.CharField(max_length=15)),
                ('caryear', models.CharField(max_length=4)),
                ('registrationno', models.CharField(max_length=10)),
                ('chassisno', models.CharField(max_length=17)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
