# Generated by Django 4.1.3 on 2022-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default='1111111111'),
        ),
    ]
